title: <p align="center"> Atharv Ganla </p>
logo: /assets/img/dp.png
description:
  <p align="center">
  <a href="assets/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/atharv-ganla/">LinkedIn</a> |
  <a href="https://github.com/atharv2007">GitHub</a>
  
  <br>   
  I am a Btech CSE 2022 graduate, currently seeking entry-level job opportunities as a Python Developer, ML Engineer, Software Developer, Data Analyst, and Data Scientist.
  I have a total of 9-months of internship experience working in Python (Flask) and ML, mainly NLP.
  <br>
  </p>
theme: jekyll-theme-minimal
